services:
  pg_db:
    image: postgres:latest

    environment:
      POSTGRES_DB: ${POSTGRES_NAME} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - ./pg_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}"]
      interval: 5s
      retries: 5

  django_app:
    build: .

    container_name: django_app 

    depends_on:
      pg_db:
        condition: service_healthy 

    ports:
      - "8000:8000"

    environment:
      POSTGRES_DB: ${POSTGRES_NAME} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: pg_db
      SECRET_KEY: ${SECRET_KEY}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

    volumes:
      - ./blog_project/static:/app/blog_project/static
      - ./blog_project/media:/app/blog_project/media
    

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - django_app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./blog_project/static:/vol/static
      - ./blog_project/media:/vol/media

volumes:
  pg_data:
  static:
  media:
