name: testing

on:
  push:
    branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        environment: Testing Environment
        env:
          DEBUG: ${{ secrets.DEBUG }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_ENGINE: ${{ secrets.DATABASE_ENGINE }}
          
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python 3.11
              uses: actions/setup-python@v2
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt    
            
            - name: Checking enviroment variables
              run: ${{ secrets.DATABASE_ENGINE}}
            - name: Run tests
              run: |
                sh -c "cd blog_project && pytest"
                