name: testing

on:
  push:
    branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        environment: Testing Environment


        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python 3.11
              uses: actions/setup-python@v2
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                python3 -m pip install --upgrade pip
                pip install -r requirements.txt    
            
            # - name: Load environment variables
            
            #     DATABASE_ENGINE:
            #     # Add other secrets/environment variables here
            #     run: |
            #       echo "DATABASE_ENGINE=$DATABASE_ENGINE" >> $GITHUB_ENV
            #       # You can now use $DATABASE_ENGINE in subsequent steps
              
            - name: Run tests
              env:
                DEBUG: ${{ secrets.DEBUG }}
                SECRET_KEY: ${{ secrets.SECRET_KEY }}
                DATABASE_ENGINE: 'sqlite3'
              run: |
                python manage.py makemigrations
                python manage.py migrate
                sh -c "cd blog_project && pytest"
                