name: testing

on:
  push:
    branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        environment: Testing Environment

        env:
          DEBUG: True
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_ENGINE: 'sqlite3'
          DATABASE_NAME: 'pg_db'

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python 3.11
              uses: actions/setup-python@v2
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                python3 -m pip install --upgrade pip
                pip install -r requirements.txt    
              
            - name: Run tests
              run: |
                cd blog_project
                python manage.py makemigrations
                python manage.py migrate
                pytest
                